#pragma once
#include <Arduino.h>

// ============================================================================
// Section 1: HTML Head (scripts, meta tags)
// AUTO-GENERATED by embed_web.py from web/ sources — do not edit manually!
// ============================================================================

const char HTML_HEAD[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html lang="en">
<head>
  <title>VentCon Pressure Control</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Load JS libraries from LittleFS root with deferred loading.-->
  <script src="/chart.min.js" defer></script>


)rawliteral";
